### ISSUE TITLE
No documentation at all about using

### ISSUE THREAD

**Issue by miraidensetsu** [eea/eea.jquery#2]
There are no documetation at all about how to use this module.

Someone that wants to use it will be forced to figure out by trial and error and reading the whole source code, that's not the best way to present it, since it consume much more time to figure out wich script do what.

**Comment by avoinea** [comment]
What about this warning:

```
Note

This add-on doesn't do anything by itself. It needs to be integrated by a developer within your own products. For reference you can check the eea.tags package.
```

Just kidding, you're right ;)
