### ISSUE TITLE
Select2 files are restricted to authenticated users

### ISSUE THREAD

**Issue by laulaz** [eea/eea.jquery#5]
We have faceted navigations and faceted searchs that should work for anonymous users.
`Select2` is used for some select widgets. It work great when logged-in. But in `eea.jquery`, the `Select2` CSS and the JS are marked to be available for authenticated users only.

As we don't see a reason why, we propose to make them available for everyone.

**Comment by laulaz** [comment]
Thank you for the merge !  Could you please make a new release ?

**Comment by avoinea** [comment]
Fixed. See https://pypi.python.org/pypi/eea.jquery
