### ISSUE TITLE
eea.jquery can be upgraded in the Plone control panel right after it is installed

### ISSUE THREAD

**Issue by fredvd** [eea/eea.jquery#8]
When I install eea.daviz in the latest 10.2 EEAKGS (docker image from https://hub.docker.com/r/eeacms/kgs/), eea.daviz installs eea.jquery as a dependency. But afterwards in the extra add'ons listing, the eea.jquery package can be upgraded (Bijwerken) to a newer profile. 
![eea-jquery-installed](https://cloud.githubusercontent.com/assets/394784/25525401/fecddd28-2c0e-11e7-9e4a-0094814be620.png)

**Comment by alecghica** [comment]
@fredvd EEA jQuery version 9.6 is the right one. I'll check why this happening but it's a minor issue you can ignore for now.

**Comment by avoinea** [comment]
Fixed.
